version: "3.3"

networks:
  frontend:

services:
  admin_app:
    image: kingwill/projects:taste-of-heaven-next_js-1.0
    container_name: "admin_app"
    ports:
      - 80:3000
    restart: always
    networks:
      - frontend
