FROM python:3.7.5-slim

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install build-essential

ENV PATH=$PATH:/usr/local/bin
ENV APP_HOME /app

RUN mkdir -p $APP_HOME 
WORKDIR $APP_HOME

COPY uwsgi.ini uwsgi.ini
COPY models models
COPY init.py init.py
COPY utils.py utils.py
COPY SES_Custom_Handler.py SES_Custom_Handler.py
COPY app.py app.py
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["uwsgi", "--ini", "uwsgi.ini"]